# Generated by Django 6.0.3 on 2026-03-11 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id_estado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'estado',
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'rol',
            },
        ),
        migrations.CreateModel(
            name='DetallePrestamo',
            fields=[
                ('id_detalle_prestamo', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.PositiveIntegerField()),
                ('herramienta', models.ForeignKey(db_column='id_codigo', on_delete=django.db.models.deletion.PROTECT, to='inventario.stock')),
            ],
            options={
                'verbose_name': 'Detalle de Préstamo',
                'verbose_name_plural': 'Detalles de Préstamo',
                'db_table': 'detalle_prestamo',
            },
        ),
        migrations.CreateModel(
            name='DevolucionHerramienta',
            fields=[
                ('id_devolucion_codigo', models.AutoField(primary_key=True, serialize=False)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('herramienta', models.ForeignKey(db_column='id_codigo', on_delete=django.db.models.deletion.PROTECT, to='inventario.stock')),
                ('id_detalle_prestamo', models.ForeignKey(db_column='id_detalle_prestamo', on_delete=django.db.models.deletion.PROTECT, related_name='devoluciones', to='prestamo.detalleprestamo')),
            ],
            options={
                'verbose_name': 'Devolución de Herramienta',
                'verbose_name_plural': 'Devoluciones de Herramientas',
                'db_table': 'devolucion_codigo',
            },
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id_prestamo', models.AutoField(primary_key=True, serialize=False)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('herramienta', models.ForeignKey(db_column='id_codigo', on_delete=django.db.models.deletion.PROTECT, to='inventario.stock')),
                ('id_estado', models.ForeignKey(db_column='id_estado', on_delete=django.db.models.deletion.PROTECT, to='prestamo.estado')),
            ],
            options={
                'verbose_name': 'Préstamo',
                'verbose_name_plural': 'Préstamos',
                'db_table': 'prestamo',
            },
        ),
        migrations.AddField(
            model_name='detalleprestamo',
            name='id_prestamo',
            field=models.ForeignKey(db_column='id_prestamo', on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='prestamo.prestamo'),
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('numero_documento', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre_completo', models.CharField(max_length=150)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(max_length=20)),
                ('tipo_documento', models.CharField(max_length=50)),
                ('id_rol', models.ForeignKey(db_column='id_rol', on_delete=django.db.models.deletion.PROTECT, to='prestamo.rol')),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
        migrations.AddField(
            model_name='prestamo',
            name='numero_documento',
            field=models.ForeignKey(db_column='numero_documento', on_delete=django.db.models.deletion.PROTECT, to='prestamo.usuario'),
        ),
    ]
