# Generated by Django 6.0.3 on 2026-03-11 01:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
        ('prestamo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleprestamo',
            name='herramienta',
            field=models.ForeignKey(db_column='id_codigo', default=1, on_delete=django.db.models.deletion.PROTECT, to='inventario.stock'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='devolucionherramienta',
            name='herramienta',
            field=models.ForeignKey(db_column='id_codigo', default=1, on_delete=django.db.models.deletion.PROTECT, to='inventario.stock'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prestamo',
            name='herramienta',
            field=models.ForeignKey(db_column='id_codigo', default=1, on_delete=django.db.models.deletion.PROTECT, to='inventario.stock'),
            preserve_default=False,
        ),
    ]
