# Generated by Django 6.0.3 on 2026-03-10 01:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BitacoraEstado',
            fields=[
                ('id_bitacora_estado', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=255)),
                ('estado', models.CharField(max_length=50)),
                ('nivel_estado', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Bitácora de Estado',
                'verbose_name_plural': 'Bitácoras de Estado',
            },
        ),
        migrations.CreateModel(
            name='BitacoraMantenimiento',
            fields=[
                ('id_mantenimiento', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_mantenimiento', models.CharField(max_length=100)),
                ('id_bitacora_estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mantenimientos', to='mantenimiento.bitacoraestado')),
            ],
            options={
                'verbose_name': 'Bitácora de Mantenimiento',
            },
        ),
        migrations.CreateModel(
            name='DetalleMantenimiento',
            fields=[
                ('id_detalle_mantenimiento', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_mantenimiento_fk', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('tipo', models.CharField(max_length=50)),
                ('id_mantenimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='mantenimiento.bitacoramantenimiento')),
            ],
        ),
    ]
