# Generated by Django 6.0.3 on 2026-03-11 19:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BitacoraEstado',
            fields=[
                ('id_bitacora_estado', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=255)),
                ('estado', models.CharField(choices=[('operativo', 'Operativo (Funcional)'), ('mantenimiento', 'En Mantenimiento'), ('limitado', 'Uso Limitado (Desgaste Medio)'), ('critico', 'Estado Crítico (Falla Inminente)'), ('fuera_servicio', 'Fuera de Servicio (Dañado)'), ('baja', 'Baja Definitiva (No Reparable)')], default='operativo', max_length=50)),
                ('nivel_estado', models.IntegerField(help_text='Escala del 1 (Pésimo) al 10 (Nuevo)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
            ],
            options={
                'verbose_name': 'Bitácora de Estado',
                'verbose_name_plural': 'Bitácoras de Estado',
            },
        ),
        migrations.CreateModel(
            name='BitacoraMantenimiento',
            fields=[
                ('id_mantenimiento', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_mantenimiento', models.CharField(choices=[('correctivo', 'Correctivo'), ('preventivo', 'Preventivo'), ('reparable', 'Reparable')], default='preventivo', max_length=100)),
                ('id_bitacora_estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mantenimientos', to='mantenimiento.bitacoraestado')),
            ],
            options={
                'verbose_name': 'Bitácora de Mantenimiento',
            },
        ),
        migrations.CreateModel(
            name='DetalleMantenimiento',
            fields=[
                ('id_detalle_mantenimiento', models.AutoField(primary_key=True, serialize=False)),
                ('motivo_mantenimiento', models.CharField(help_text='Escriba brevemente el motivo de este detalle (ej: Desgaste de pieza)', max_length=255)),
                ('descripcion', models.TextField(help_text='Descripción detallada del trabajo realizado')),
                ('tipo', models.CharField(max_length=50)),
                ('id_mantenimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='mantenimiento.bitacoramantenimiento')),
            ],
            options={
                'verbose_name': 'Detalle de Mantenimiento',
                'verbose_name_plural': 'Detalles de Mantenimientos',
            },
        ),
    ]
