# Generated by Django 6.0.3 on 2026-03-10 01:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitacoraestado',
            name='estado',
            field=models.CharField(choices=[('operativo', 'Operativo (Funcional)'), ('mantenimiento', 'En Mantenimiento'), ('limitado', 'Uso Limitado (Desgaste Medio)'), ('critico', 'Estado Crítico (Falla Inminente)'), ('fuera_servicio', 'Fuera de Servicio (Dañado)'), ('baja', 'Baja Definitiva (No Reparable)')], default='operativo', max_length=50),
        ),
        migrations.AlterField(
            model_name='bitacoraestado',
            name='nivel_estado',
            field=models.IntegerField(help_text='Escala del 1 (Pésimo) al 10 (Nuevo)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='bitacoramantenimiento',
            name='tipo_mantenimiento',
            field=models.CharField(choices=[('correctivo', 'Correctivo'), ('preventivo', 'Preventivo'), ('reparable', 'Reparable')], default='preventivo', max_length=100),
        ),
    ]
