# Generated by Django 6.0.3 on 2026-03-10 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0002_alter_bitacoraestado_estado_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detallemantenimiento',
            options={'verbose_name': 'Detalle de Mantenimiento', 'verbose_name_plural': 'Detalles de Mantenimientos'},
        ),
        migrations.RemoveField(
            model_name='detallemantenimiento',
            name='tipo_mantenimiento_fk',
        ),
        migrations.AddField(
            model_name='detallemantenimiento',
            name='motivo_mantenimiento',
            field=models.CharField(default='sin motivo', help_text='Escriba brevemente el motivo de este detalle (ej: Desgaste de pieza)', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='detallemantenimiento',
            name='descripcion',
            field=models.TextField(help_text='Descripción detallada del trabajo realizado'),
        ),
    ]
